---
- name: "Setup users"
  hosts: instance1
  vars:
    users:
      - { name: test_user1, uid: 1003 }
      - { name: test_user2, uid: 1004 }
  tasks: 
    - name: "Create users"
      user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
      with_items: "{{ users }}"
