---
- name: "Install Docker"
  hosts: instance1
  tasks: 
    - name: "Install dependencies"
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - yum-utils 
        - lvm2
        - device-mapper-persistent-data
   # Install Docker task...  
