---
- name: Converge
  hosts: all
  tasks:
    - name: Add user john
      user:
        name: john
    - name: Add user mike
      user: 
        name: mike
    - include_role:
        name: "infra"
