---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance1
    image: pycontribs/debian
    pre_build_image: true
    exposed_ports:
      - 8080/tcp
    published_ports:
      - 0.0.0.0:8080:8080/tcp
      - 0.0.0.0:9090:9090/tcp
  - name: instance2
    image: pycontribs/debian
    pre_build_image: true
  - name: instance3
    image: pycontribs/debian
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
