---
- name: Install node
  yum:
    name: nodejs
    state: latest
  
- name: Install forever
  npm:
    name: forever
    state: latest
    global: yes 

- debug:
    msg: "App directory: {{ app_dir }}"

- name: Template provisioning summary file
  template: 
    src: summary.txt.j2
    dest: /root/summary.txt
