---
- name: Install node
  yum:
    name: nodejs
    state: latest
  
- name: Install forever
  npm:
    name: forever
    version: "{{ forever_version }}"
    global: yes 

- name: Template summary file
  template: 
    src: summary.txt.j2
    dest: ~/summary.txt

- name: prueba
  debug:
    msg: "Esto es una prueba"
