---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: pb_test_instance1
    image: python:bullseye
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ../../playbook.yml
  inventory:
    links:
      hosts: ../../inventory/local
verifier:
  name: ansible
