---
- name: "Run Node app"
  hosts: instance1
  vars_files: 
    - vars.yml
  tasks:
    - name: "Install Node"
      yum:
        name: nodejs
        state: latest
    - name: "Install 'forever'"
      npm:
        name: forever
        state: latest
        global: yes
    - name: "Copy server.js"
      copy: 
        src: server.js
        dest: ~/server.js
    - name: "Start app"
      shell: PORT={{ server_port }} forever start ~/server.js
    - name: "Smoke test"
      get_url:
        url: http://localhost:{{ server_port }}/
        dest: ~/response.json
      become: yes
      become_user: john
