---
- name: Deploy Node App
  hosts: instance1
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
    - name: Install sudo
      apt:
        name: sudo
        state: latest
  tasks:
    - name: Install Node
      apt:
        name: nodejs
        state: latest
    - name: Install npm
      apt:
        name: npm
        state: latest
    - name: Install forever
      npm:
        name: forever
        state: latest
        global: true
    - name: Copy source code
      copy: 
        src: server.js
        dest: ~/server.js
      register: source_code
    - name: List running apps
      command: forever list
      changed_when: false
      register: forever_list
    - set_fact:
        is_running: "{{ forever_list.stdout.find('server.js') != -1 }}"
        new_version: "{{ source_code.changed }}"
    - name: Start application
      shell: PORT={{ server_port }} forever start ~/server.js
      when: not is_running
      notify: started
    - name: Start new version
      shell: PORT={{ server_port }} forever restart ~/server.js
      when: is_running and new_version
      notify: started

  handlers:
    - name: Smoke test
      listen: started
      get_url:
        url: http://localhost:{{ server_port }}/
        dest: ~/response.json
      become: true
      become_user: john
