---
- name: "Run Node app"
  hosts: instance1
  pre_tasks:
    - name: Update yum packages
      yum: 
        update_cache: yes
  tasks:
    - name: "Install Node"
      yum:
        name: nodejs
        state: latest
    - name: "Install 'forever'"
      npm:
        name: forever
        state: latest
        global: yes
    - name: "Copy server.js"
      copy: 
        src: "server.js"
        dest: "~/server.js"
    - name: "Start app"
      command: "forever start ~/server.js"
    - name: "Smoke test"
      get_url:
        url: http://localhost:8080/
        dest: ~/response.json
      become: yes
      become_user: john
