---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: test_instance
    image: python:bullseye
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - syntax 
    - create
    - converge
    - verify
    - destroy
   
