---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - apt:
        name: nodejs
        state: present
      register: nodejs_status
    - name: nodejs is installed
      assert:
        that: "{{ nodejs_status.changed }} is false"
    - npm:
        name: forever
        state: present
        global: true
      register: forever_status
    - name: forever is installed
      assert:
        that: "{{ forever_status.changed }} is false"
